#!/usr/bin/env bash
# Development tools configuration
# Auto-generated by devtools-installer.sh

# Ensure nvm is loaded
export NVM_DIR="${NVM_DIR:-$HOME/.local/share/nvm}"
[ -s "$NVM_DIR/nvm.sh" ] && {
    set +u
    \. "$NVM_DIR/nvm.sh"
    set -u
}

# Ensure pyenv is loaded
export PYENV_ROOT="$HOME/.pyenv"
[ -d "$PYENV_ROOT" ] && {
    export PATH="$PYENV_ROOT/bin:$PATH"
    command -v pyenv >/dev/null && eval "$(pyenv init -)"
}

# direnv
command -v direnv >/dev/null 2>&1 && eval "$(direnv hook bash)"

# zoxide
command -v zoxide >/dev/null 2>&1 && eval "$(zoxide init bash)"

# bat aliases (Ubuntu packages it as batcat)
command -v batcat >/dev/null 2>&1 && {
    alias cat='batcat'
    alias less='batcat --paging=always'
}

# fd alias (Ubuntu packages it as fdfind)
command -v fdfind >/dev/null 2>&1 && alias fd='fdfind'

# Python aliases
alias py='python3'
alias venv='python3 -m venv'
alias activate='source venv/bin/activate 2>/dev/null || source .venv/bin/activate'

# Git aliases (additional)
alias gcm='git checkout main 2>/dev/null || git checkout master'
alias gfo='git fetch origin'

# Set default editors
export EDITOR="${EDITOR:-vim}"
export VISUAL="${VISUAL:-$EDITOR}"
